language: node_js
services:
    - mongodb
addons:
    apt:
        sources:
        - mongodb-3.0-precise
        packages:
        - mongodb-org-server
before_script:
    - sleep 15
    - mongo url-shortener --eval 'db.url.createIndex({short:1}, {unique:true});' 
